/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Johannes
 */

import java.util.IllegalFormatException;
import java.util.InputMismatchException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tagLine = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        amountLabel = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tagLine.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        tagLine.setText("Tax Calculator");

        salaryLabel.setText("Annual Salary:  R");

        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });

        ageLabel.setText("Age: ");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        amountLabel.setText("Taxable Amount: R ");

        amount.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tagLine)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submit)
                        .addGap(157, 157, 157))))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amountLabel)
                    .addComponent(ageLabel)
                    .addComponent(salaryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salary)
                    .addComponent(age)
                    .addComponent(amount, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tagLine)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryLabel)
                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try{
            double sal = Double.parseDouble(salary.getText());
            int howOld = Integer.parseInt(age.getText());
            double result;
            if(howOld<0 || sal<0){
                throw new NumberFormatException("No negative numbers Please");
            }
            
            if(sal<=216200){
                result = sal*0.18;
                if(howOld<65 && result>87300){
                    result = 87300;
                }else if((howOld>=65 && howOld<75) && result>87300){
                    result = 135150;
                }else if(howOld>75 && result>87300){
                    result = 151100;
                }
                amount.setText(Double.toString(result));
            }else if(sal>216200 && sal<=337800){
                result = 38916 + (sal*0.26);
                if(howOld<65 && result>87300){
                    result = 87300;
                }else if((howOld>=65 && howOld<75) && result>87300){
                    result = 135150;
                }else if(howOld>75 && result>87300){
                    result = 151100;
                }
                amount.setText(Double.toString(result));
            }else if(sal>337800 && sal<= 467500){
                result = 70532+(sal*0.31);
                if(howOld<65 && result>87300){
                    result = 87300;
                }else if((howOld>=65 && howOld<75) && result>87300){
                    result = 135150;
                }else if(howOld>75 && result>87300){
                    result = 151100;
                }
                amount.setText(Double.toString(result));
            }else if(sal>467500 && sal<=613600){
                result = 110739+(sal*0.36);
                if(howOld<65 && result>87300){
                    result = 87300;
                }else if((howOld>=65 && howOld<75) && result>87300){
                    result = 135150;
                }else if(howOld>75 && result>87300){
                    result = 151100;
                }
                amount.setText(Double.toString(result));
            }else if(sal>613600 && sal<=782200){
                result = 163335*(sal*0.39);
                if(howOld<65 && result>87300){
                    result = 87300;
                }else if((howOld>=65 && howOld<75) && result>87300){
                    result = 135150;
                }else if(howOld>75 && result>87300){
                    result = 151100;
                }
                amount.setText(Double.toString(result));
            }if(sal>782200 && sal<=1656600){
                result = 229089+(sal*0.41);
                if(howOld<65 && result>87300){
                    result = 87300;
                }else if((howOld>=65 && howOld<75) && result>87300){
                    result = 135150;
                }else if(howOld>75 && result>87300){
                    result = 151100;
                }
                amount.setText(Double.toString(result));
            }if(sal>1656600){
                result = 587593+(sal*0.45);
                if(howOld<65 && result>87300){
                    result = 87300;
                }else if((howOld>=65 && howOld<75) && result>87300){
                    result = 135150;
                }else if(howOld>75 && result>87300){
                    result = 151100;
                }
                amount.setText(Double.toString(result));
            }
        }catch(NumberFormatException e){
        
            JOptionPane.showMessageDialog(new JFrame(), "Please enter the right format for age and salary");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField salary;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JButton submit;
    private javax.swing.JLabel tagLine;
    // End of variables declaration//GEN-END:variables
}
